// DGrok Delphi parser
// Copyright (C) 2007 Joe White
// http://www.excastle.com/dgrok
//
// Licensed under the Open Software License version 3.0
// http://www.opensource.org/licenses/osl-3.0.php
using System;
using System.Collections.Generic;
using System.Text;

namespace DGrok.Framework
{
    public enum RuleType
    {
        AddOp,
        ArrayType,
        AssemblerStatement,
        Atom,
        BareInherited,
        Block,
        ClassOfType,
        ClassType,
        ConstantDecl,
        ConstSection,
        ContainsClause,
        Directive,
        EnumeratedType,
        EnumeratedTypeElement,
        ExportsItem,
        ExportsSpecifier,
        ExportsStatement,
        Expression,
        ExpressionList,
        ExpressionOrAssignment,
        ExpressionOrRange,
        ExpressionOrRangeList,
        ExtendedIdent,
        Factor,
        FancyBlock,
        FieldDecl,
        FieldSection,
        FileType,
        Goal,
        GotoStatement,
        Ident,
        IdentList,
        IfStatement,
        ImplementationDecl,
        ImplementationSection,
        InitSection,
        InterfaceDecl,
        InterfaceSection,
        InterfaceType,
        LabelDeclSection,
        LabelId,
        MethodHeading,
        MethodImplementation,
        MethodOrProperty,
        MethodReturnType,
        MulOp,
        OpenArray,
        Package,
        PackedType,
        Parameter,
        ParameterType,
        ParenthesizedExpression,
        Particle,
        PointerType,
        PortabilityDirective,
        ProcedureType,
        Program,
        Property,
        PropertyDirective,
        QualifiedIdent,
        RaiseStatement,
        RecordFieldConstant,
        RecordType,
        RelOp,
        RequiresClause,
        SetLiteral,
        SetType,
        SimpleExpression,
        SimpleStatement,
        Statement,
        StringType,
        Term,
        Type,
        TypedConstant,
        TypeDecl,
        TypeSection,
        UnaryOperator,
        Unit,
        UsedUnit,
        UsesClause,
        VarDecl,
        VarSection,
        Visibility,
        VisibilitySection,
        VisibilitySectionContent,
    }
}
