require 'yaml'

def fieldname(s)
  "_" + s.sub(/^[A-Z]/) {|m| m.downcase}
end
def varname(s)
  result = s.sub(/^[A-Z]/) {|m| m.downcase}
  if %w|class const default goto in interface object operator string|.include?(result)
    result = "the" + s
  end
  result
end

cs = []
cs << IO.read('osl-notice.txt')
cs << "// Autogenerated file - do not edit"
cs << ""
cs << "using System;"
cs << "using System.Collections.Generic;"
cs << "using System.Text;"
cs << ""
cs << "namespace DGrok.Framework"
cs << "{"

data = YAML.load_file("CodeGen.yaml")
node_types = data['NodeTypes']
node_types.keys.sort_by {|i| i.downcase}.each do |type_name|
  fail "Node classes must end with 'Node'" if type_name !~ /Node$/
  property_names = node_types[type_name]
  sorted_property_names = property_names.sort_by {|i| i.downcase}
  cs << "    public class #{type_name} : NonterminalNode"
  cs << "    {"
  sorted_property_names.each do |prop|
    cs << "        private AstNode #{fieldname(prop)};"
  end
  cs << ""
  params = property_names.map {|item| "AstNode " + varname(item)}
  cs << "        public #{type_name}(#{params.join(', ')})"
  cs << "        {"
  property_names.each do |prop|
    cs << "            #{fieldname(prop)} = #{varname(prop)};"
  end
  cs << "        }"
  cs << ""
  sorted_property_names.each do |prop|
    cs << "        public AstNode #{prop}"
    cs << "        {"
    cs << "            get { return #{fieldname(prop)}; }"
    cs << "        }"
  end
  cs << ""
  cs << "        public override " +
    "IEnumerable<KeyValuePair<string, AstNode>> Properties"
  cs << "        {"
  cs << "            get"
  cs << "            {"
  property_names.each do |prop|
    cs << "                yield return new " +
      "KeyValuePair<string, AstNode>(\"#{prop}\", #{prop});"
  end
  cs << "            }"
  cs << "        }"
  cs << "    }"
end

cs << "}"
cs_text = cs.join("\n") + "\n"
cs_filename = "DGrok.Framework/Framework/GeneratedNodes.cs"
if !File.exist?(cs_filename) || cs_text != IO.read(cs_filename)
  File.open(cs_filename, "w") do |file|
    file.write(cs_text)
  end
end